# rm tmp dirs
rm -rf .aci_pre
rm -rf .aci_post
rm -rf .aci_main
rm -rf .aks
rm -rf output_dir
rm -rf content_dir

# rm downloaded video and audio files
rm *.mp4
rm *.mp4.*
rm *.mp3

# rm jnl files from azcopy
rm -rf *.jnl

# rm files generated by notebooks
rm aks/Dockerfile
rm aks/requirements.txt
rm aks_deployment.json
rm aci/Dockerfile
rm aci/requirements.txt
rm logic_app.json

# reset kubectl config 
rm ~/.kube/config
